name: gulmate
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  dots_indicator: ^1.1.0
  google_sign_in: ^4.1.1
  flutter_facebook_login: ^3.0.0
  flutter_launcher_icons: ^0.7.4
  dio: ^3.0.8
  pin_entry_text_field: ^0.1.4
  font_awesome_flutter: ^8.5.0
  shared_preferences: ^0.5.6+1
  flutter_datetime_picker: ^1.3.4
  flutter_slidable: ^0.5.4
  enum_to_string: ^1.0.8
  simple_gesture_detector: ^0.1.4
  intl: ^0.16.1
  rxdart: ^0.23.1
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  equatable: ^1.0.3
  get_it: ^3.1.0
  stomp_dart_client: ^0.2.3
  flutter_local_notifications: ^1.2.0+3
  flutter_colorpicker: ^0.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "images/gulmate_app_icon.svg"

module:
  androidX: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Spoqa
      fonts:
        - asset: fonts/Spoqa-Han-Sans-Regular.ttf
        - asset: fonts/Spoqa-Han-Sans-Bold.ttf
          weight: 700
        - asset: fonts/Spoqa-Han-Sans-Light.ttf
          weight: 300
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/gulmate-logo.png
    - images/gulmate_app_icon.svg
    - images/logo_symbol/
    - images/profile_placeholder.png
    - config/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

#        - asset: fonts/Spoqa-Han-Sans-Thin.ttf
#          weight: 100
#        - asset: fonts/Spoqa-Han-Sans-Light.ttf
#          weight: 300
#        - asset: fonts/Spoqa-Han-Sans-Bold.ttf
#          weight: 700
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
